server {
    listen 80;
    listen [::]:80;
    server_name varocheck.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://www.varocheck.com$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name www.varocheck.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name api.varocheck.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name varocheck.com;

    ssl_certificate /etc/letsencrypt/live/varocheck.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/varocheck.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        return 301 https://www.varocheck.com$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.varocheck.com;

    ssl_certificate /etc/letsencrypt/live/varocheck.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/varocheck.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $frontend_upstream frontend;
        proxy_pass http://$frontend_upstream:3000;
        include /etc/nginx/includes/proxy-common.conf;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name api.varocheck.com;

    client_max_body_size 10m;
    ssl_certificate /etc/letsencrypt/live/varocheck.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/varocheck.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $backend_upstream backend;
        proxy_pass http://$backend_upstream:4000;
        include /etc/nginx/includes/proxy-common.conf;
    }
}
