export const APP_ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INPUT_VALIDATION_ERROR: "INPUT_VALIDATION_ERROR",
  CONFIG_VALIDATION_ERROR: "CONFIG_VALIDATION_ERROR",
  SOURCE_SEARCH_FAILED: "SOURCE_SEARCH_FAILED",
  EXTRACTION_FAILED: "EXTRACTION_FAILED",
  LLM_SCHEMA_ERROR: "LLM_SCHEMA_ERROR",
  REVIEW_PARTIAL: "REVIEW_PARTIAL",
} as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
