server {
    listen 80;
    listen [::]:80;
    server_name www.varocheck.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $frontend_upstream frontend;
        proxy_pass http://$frontend_upstream:3000;
        include /etc/nginx/includes/proxy-common.conf;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name api.varocheck.com;

    client_max_body_size 10m;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        resolver 127.0.0.11 ipv6=off valid=30s;
        set $backend_upstream backend;
        proxy_pass http://$backend_upstream:4000;
        include /etc/nginx/includes/proxy-common.conf;
    }
}
